# Generated by Django 2.2.16 on 2022-12-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221203_1206'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
    ]
